// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQEC4-Isgk47A_W2gBqrRPCFjhNxD9DEM',
    appId: '1:277814905775:web:8aa8eab6b415646cbcbd5a',
    messagingSenderId: '277814905775',
    projectId: 'guardiancircle-8d1ae',
    authDomain: 'guardiancircle-8d1ae.firebaseapp.com',
    storageBucket: 'guardiancircle-8d1ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzNcNyCODMxJZtbriNGbpL7i701k7lNzc',
    appId: '1:277814905775:android:a0bbfcd5abdc54aebcbd5a',
    messagingSenderId: '277814905775',
    projectId: 'guardiancircle-8d1ae',
    storageBucket: 'guardiancircle-8d1ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIOU3hCSTmsg26G3ZMFdegFAaIFc5AuCU',
    appId: '1:277814905775:ios:9d7bc2aa6c4333bfbcbd5a',
    messagingSenderId: '277814905775',
    projectId: 'guardiancircle-8d1ae',
    storageBucket: 'guardiancircle-8d1ae.firebasestorage.app',
    iosBundleId: 'com.example.guardiancircle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIOU3hCSTmsg26G3ZMFdegFAaIFc5AuCU',
    appId: '1:277814905775:ios:9d7bc2aa6c4333bfbcbd5a',
    messagingSenderId: '277814905775',
    projectId: 'guardiancircle-8d1ae',
    storageBucket: 'guardiancircle-8d1ae.firebasestorage.app',
    iosBundleId: 'com.example.guardiancircle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQEC4-Isgk47A_W2gBqrRPCFjhNxD9DEM',
    appId: '1:277814905775:web:885c3ae9a7bdc457bcbd5a',
    messagingSenderId: '277814905775',
    projectId: 'guardiancircle-8d1ae',
    authDomain: 'guardiancircle-8d1ae.firebaseapp.com',
    storageBucket: 'guardiancircle-8d1ae.firebasestorage.app',
  );
}
